server:
  port: 8080


spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 200MB
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

